FROM denoland/deno
WORKDIR /chesswar

# Load dependencies
COPY deps.ts deno.json deno.lock ./
RUN deno cache deps.ts

# Build
COPY common common
COPY server server

# Run
EXPOSE 18357
CMD deno task server
